### ISSUE TITLE
Any plan for a dashboard?

### ISSUE THREAD

**Issue by bbigras** [purplg/hass#5]
So we can control and see all my stuff within Emacs.

**Comment by purplg** [comment]
I've thought about it and that was initially the plan when I started this project. It's a feature I'd love to add one day. The ground work is there now so maybe I'll work on that soon

**Comment by purplg** [comment]
I've been able to make a lot of progress on this already! I'd be happy if you'd be willing to try it out so far. It's in the `dashboard` branch. I still have a lot of testing to do, code cleanup, and documentation writing, but I think it's in a decent state so far.

If you use straight, you can use this recipe `:straight (:type git :host github :repo "purplg/hass" :branch "dashboard")`

I'd like to be able to add "rows" of widgets in the future, but that'd add a decent amount of additional complexity and I haven't decided on a good way to do it, so I'll hold off on that for now. Also I haven't done anything, except color the icons blue and make the group names larger, on the appearance of the dashboard. Eventually I wanna make it prettier and customizable.

If you have any other suggestions or ideas, I'd be happy to hear them.

The basic required setup is to configure `hass-dash-layout` according to the example in the docstring for that variable. Then you can call `(hass-dash-open)` and it'll open the dashboard. I can help you with setup if you decide to try it out. I realize the documentation is a bit lacking right now.

**Comment by bbigras** [comment]
Awesome :tada: !!

With the `dashboard` branch I got this when I run `(hass-setup)`. I'm not using `straight` btw, since I'm using a special nixos emacs config.

```
#s(request-response nil nil nil nil nil "https://my_url:443/api/" nil (:sync nil :type "GET" :headers (("User-Agent" . hass--user-agent) ("Authorization" . "Bearer my_token") ("Content-Type" . "application/json")) :data nil :parser #[0 "ÀÁ !" [hass--deserialize buffer-string] 2] :error hass--request-error ...) #<buffer  *request curl*-43543> nil nil ...)
```

No trace if I enable `toggle-debug-on-error`.

**Comment by purplg** [comment]
Thanks for testing!

I don't think that's an error but rather just a request object being returned that doesn't need to be and it outputs to the minibuffer. I've commit a change to fix that, something I should have done a long time ago haha.

Do `hass--available-entities` and `hass--available-services` populate after `hass-setup` is called?

**Comment by purplg** [comment]
Ah that's an important thing to handle! Good catch, I'll be sure to fix that soon

**Comment by purplg** [comment]
Should work now.

I also added the default service for a scene as `scene.turn_on` so you no longer need to specify that `:service` if that's what you're calling. I'll be adding more before release.

**Comment by bbigras** [comment]
Just tested. it works. thanks!

Btw, the first request takes a while.

**Comment by bbigras** [comment]
> Btw, the first request takes a while.

It might be only on my side. I think I saw something similar with the normal HA dashboard.

**Comment by purplg** [comment]
> Any recommended key binding for `(hass-dash-open)`?

As an Evil and former Doom user, I'm using `SPC-a-d` for `hass-dash-open`. `SPC-a-c` for `hass-call-service`. Works well for me.

**Comment by purplg** [comment]
@bbigras Thanks for your suggestion and help! Sorry it took so long to complete this. Been very busy with life lately. Let me know if you find any issues or have any other suggestions. :)
