### ISSUE TITLE
Nothing happening upon calling hass-call-service

### ISSUE THREAD

**Issue by RidaAyed** [purplg/hass#52]
Thank you for that very useful piece of software :rocket: 

After re-installing spacemacs, calling `hass-call-service` leads nowhere. The message buffer remains empty nor is any error raised after enabling `spacemacs/debug-on-error`. 

How can I debug this behavior?

**Comment by purplg** [comment]
Hi, I'm glad you find it useful! ^^

Does it give you an `Entity:` prompt in the minibuffer when you?

If so, what's the value of `hass--available-entities`?

If it's empty, it may be that `(hass-setup)` isn't connecting and populated the entities on your Home Assistant instance.

**Comment by RidaAyed** [comment]
Adding the additional `(hass-ensure)` at the bottom solved it.

    (use-package hass
      :ensure t
      :init
      (setq hass-host "foo")
      (setq hass-insecure t)
      (setq hass-apikey (lambda () (auth-source-pass-get 'secret "emacs-apikey")))
      (hass-ensure)
      )
